{
  "openapi": "3.0.0",
  "paths": {
    "/api": {
      "get": {
        "operationId": "AppController_getHello",
        "summary": "あいさつ取得",
        "description": "あいさつを取得する。",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfGetHelloResponse",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/GetHelloResponse"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/signup": {
      "post": {
        "operationId": "AuthController_signup",
        "summary": "ユーザ登録",
        "description": "ユーザを登録する。",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfUserResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/UserResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/login": {
      "post": {
        "operationId": "AuthController_login",
        "summary": "ログイン",
        "description": "ログインする。",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequestDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfLoginResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/LoginResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}": {
      "get": {
        "operationId": "UsersController_findOne",
        "summary": "ユーザ取得",
        "description": "ユーザを取得する。",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfUserResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/UserResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "UsersController_remove",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfUserResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/UserResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/playlists": {
      "patch": {
        "operationId": "UsersController_updatePlaylist",
        "summary": "ユーザのプレイリスト更新",
        "description": "ユーザのプレイリストを更新する。",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfUserResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/UserResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/spotify/albums": {
      "get": {
        "operationId": "SpotifyController_findAlbums",
        "summary": "楽曲検索",
        "description": "楽曲名からアルバムを検索する。",
        "parameters": [
          {
            "name": "limit",
            "required": false,
            "in": "query",
            "description": "pagination size",
            "schema": {
              "example": 20,
              "type": "number"
            }
          },
          {
            "name": "offset",
            "required": false,
            "in": "query",
            "description": "pagination offset",
            "schema": {
              "example": 0,
              "type": "number"
            }
          },
          {
            "name": "albumName",
            "required": true,
            "in": "query",
            "description": "query of album name",
            "schema": {
              "example": "千本桜",
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfFindAlbumsResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/FindAlbumsResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/spotify/artists": {
      "get": {
        "operationId": "SpotifyController_findArtists",
        "summary": "アーティスト検索",
        "description": "アーティスト名からアーティストを検索する。",
        "parameters": [
          {
            "name": "limit",
            "required": false,
            "in": "query",
            "description": "pagination size",
            "schema": {
              "example": 20,
              "type": "number"
            }
          },
          {
            "name": "offset",
            "required": false,
            "in": "query",
            "description": "pagination offset",
            "schema": {
              "example": 0,
              "type": "number"
            }
          },
          {
            "name": "artistName",
            "required": true,
            "in": "query",
            "description": "query of artist name",
            "schema": {
              "example": "初音ミク",
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfFindArtistsResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/FindArtistsResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/spotify/artists/{id}/albums": {
      "get": {
        "operationId": "SpotifyController_findArtistAlbums",
        "summary": "アーティストの楽曲検索",
        "description": "アーティストからアルバムを検索する。",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "required": false,
            "in": "query",
            "description": "pagination size",
            "schema": {
              "example": 20,
              "type": "number"
            }
          },
          {
            "name": "offset",
            "required": false,
            "in": "query",
            "description": "pagination offset",
            "schema": {
              "example": 0,
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "title": "ApiCommonResponseOfFindArtistAlbumsResponseDto",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/CommonResponseDto"
                    },
                    {
                      "properties": {
                        "data": {
                          "type": "object",
                          "$ref": "#/components/schemas/FindArtistAlbumsResponseDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "info": {
    "title": "api example",
    "description": "The API description",
    "version": "1.0",
    "contact": {}
  },
  "tags": [
    {
      "name": "example",
      "description": ""
    }
  ],
  "servers": [],
  "components": {
    "schemas": {
      "CommonResponseDto": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "description": "実行結果",
            "example": true
          },
          "date": {
            "format": "date-time",
            "type": "string",
            "description": "レスポンス送信日時",
            "example": "2024-03-12T07:45:29.583Z"
          },
          "data": {
            "type": "object",
            "description": "データ"
          },
          "error": {
            "type": "string",
            "description": "エラー内容",
            "example": []
          }
        },
        "required": [
          "success",
          "date",
          "data",
          "error"
        ]
      },
      "GetHelloResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "メッセージ",
            "example": "Hello World!"
          }
        },
        "required": [
          "message"
        ]
      },
      "ArtistResponseDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "id",
            "example": 1
          },
          "name": {
            "type": "string",
            "description": "name",
            "example": "artist name"
          }
        },
        "required": [
          "id",
          "name"
        ]
      },
      "AlbumResponseDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "id",
            "example": 1
          },
          "name": {
            "type": "string",
            "description": "name",
            "example": "album name"
          },
          "releaseDate": {
            "type": "string",
            "description": "releaseDate",
            "example": "2021-01-01"
          },
          "artists": {
            "description": "artists",
            "example": [
              {
                "id": 1,
                "name": "artist name"
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ArtistResponseDto"
            }
          }
        },
        "required": [
          "id",
          "name",
          "releaseDate",
          "artists"
        ]
      },
      "PlayListResponseDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "id",
            "example": 1
          },
          "albums": {
            "description": "albums",
            "example": [
              {
                "id": 1,
                "name": "album name",
                "releaseDate": "2021-01-01",
                "artists": [
                  {
                    "id": 1,
                    "name": "artist name"
                  }
                ]
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AlbumResponseDto"
            }
          }
        },
        "required": [
          "id",
          "albums"
        ]
      },
      "UserResponseDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "name",
            "example": "nickname"
          },
          "playlists": {
            "description": "playlists",
            "example": [
              {
                "id": 1,
                "albums": [
                  {
                    "id": 1,
                    "name": "album name",
                    "releaseDate": "2021-01-01",
                    "artists": [
                      {
                        "id": 1,
                        "name": "artist name"
                      }
                    ]
                  }
                ]
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PlayListResponseDto"
            }
          }
        },
        "required": [
          "name",
          "playlists"
        ]
      },
      "CreateUserDto": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "Email",
            "example": "test@example.com"
          },
          "password": {
            "type": "string",
            "description": "password",
            "example": "password"
          },
          "name": {
            "type": "string",
            "description": "name",
            "example": "nickname"
          }
        },
        "required": [
          "email",
          "password",
          "name"
        ]
      },
      "LoginResponseDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "user id",
            "example": "1"
          },
          "name": {
            "type": "string",
            "description": "user name",
            "example": "test name"
          },
          "access_token": {
            "type": "string",
            "description": "jwt token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTcyNjY0NzQ5MywiZXhwIjoxNzI2NjQ4NjkzfQ.Ac7bLt8f6JoshNX_V0hbbJZj_3LfGcupY3ffFQRKpak"
          }
        },
        "required": [
          "id",
          "name",
          "access_token"
        ]
      },
      "LoginRequestDto": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "Email",
            "example": "test@example.com"
          },
          "password": {
            "type": "string",
            "description": "password",
            "example": "password"
          }
        },
        "required": [
          "email",
          "password"
        ]
      },
      "UpdateUserDto": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "Email",
            "example": "test@example.com"
          },
          "password": {
            "type": "string",
            "description": "password",
            "example": "password"
          },
          "name": {
            "type": "string",
            "description": "name",
            "example": "nickname"
          },
          "playlists": {
            "description": "playlists",
            "example": [
              {
                "id": 1,
                "albums": [
                  {
                    "name": "album name",
                    "releaseDate": "2021-01-01",
                    "artists": [
                      {
                        "name": "artist name"
                      }
                    ]
                  }
                ]
              }
            ],
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "playlists"
        ]
      },
      "ArtistDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "artist id",
            "example": "1"
          },
          "name": {
            "type": "string",
            "description": "artist name",
            "example": "初音ミク"
          }
        },
        "required": [
          "id",
          "name"
        ]
      },
      "AlbumDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "album id",
            "example": "1"
          },
          "name": {
            "type": "string",
            "description": "album name",
            "example": "千本桜"
          },
          "releaseDate": {
            "type": "string",
            "description": "album release date",
            "example": "2021-01-01"
          },
          "detail": {
            "type": "string",
            "description": "album detail url",
            "example": "https://example.com"
          },
          "artists": {
            "description": "album artists",
            "example": [
              {
                "id": "1",
                "name": "初音ミク"
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ArtistDto"
            }
          }
        },
        "required": [
          "id",
          "name",
          "releaseDate",
          "detail",
          "artists"
        ]
      },
      "FindAlbumsResponseDto": {
        "type": "object",
        "properties": {
          "total": {
            "type": "number",
            "description": "pagination size",
            "example": 20
          },
          "limit": {
            "type": "number",
            "description": "pagination size",
            "example": 20
          },
          "offset": {
            "type": "number",
            "description": "pagination offset",
            "example": 0
          },
          "albums": {
            "description": "album list",
            "example": [
              {
                "id": "1",
                "name": "千本桜",
                "releaseDate": "2021-01-01",
                "detail": "https://example.com",
                "artists": [
                  {
                    "id": "1",
                    "name": "初音ミク"
                  }
                ]
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AlbumDto"
            }
          }
        },
        "required": [
          "total",
          "limit",
          "offset",
          "albums"
        ]
      },
      "FindArtistsResponseDto": {
        "type": "object",
        "properties": {
          "total": {
            "type": "number",
            "description": "pagination size",
            "example": 20
          },
          "limit": {
            "type": "number",
            "description": "pagination size",
            "example": 20
          },
          "offset": {
            "type": "number",
            "description": "pagination offset",
            "example": 0
          },
          "artists": {
            "description": "artist list",
            "example": [
              {
                "id": "1",
                "name": "初音ミク"
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ArtistDto"
            }
          }
        },
        "required": [
          "total",
          "limit",
          "offset",
          "artists"
        ]
      },
      "FindArtistAlbumsResponseDto": {
        "type": "object",
        "properties": {
          "total": {
            "type": "number",
            "description": "pagination size",
            "example": 20
          },
          "limit": {
            "type": "number",
            "description": "pagination size",
            "example": 20
          },
          "offset": {
            "type": "number",
            "description": "pagination offset",
            "example": 0
          },
          "artist": {
            "description": "album list",
            "example": {
              "id": "1",
              "name": "初音ミク"
            },
            "allOf": [
              {
                "$ref": "#/components/schemas/ArtistDto"
              }
            ]
          },
          "albums": {
            "description": "album list",
            "example": [
              {
                "id": "1",
                "name": "千本桜",
                "releaseDate": "2021-01-01",
                "detail": "https://example.com",
                "artists": [
                  {
                    "id": "1",
                    "name": "初音ミク"
                  }
                ]
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AlbumDto"
            }
          }
        },
        "required": [
          "total",
          "limit",
          "offset",
          "artist",
          "albums"
        ]
      }
    }
  }
}